dist: trusty
sudo: required

language: node_js
node_js: "node"

before_install:
 - npm install -g npm

install:
  - npm install

before_script:
  - npm install -g firebase-tools

script:
  - ng test --single-run
  - ng build --prod

after_success:
  - ./deploy.sh

notifications:
  email:
    on_failure: change
    on_success: change
